name: "deploy logic app subscriptions"

on:
  push:
    branches: ["feature/logic_app_subscriptions"]


jobs:
  deploy-template-subscriptions:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
          enable-AzPSSession: true 

      - name: deploy template
        id: deploy
        uses: azure/powershell@v1
        with: 
          inlineScript: |
            az deployment group create -g stmanageaubscriptions --template-file ./templates/template.json 
          azPSVersion: latest

