name: 'Logic App Workflow on workflow_dispatch'

on:
  push: 
    branches: ["feature/logic_app_workflow"]
  pull_request:
    branches: ["feature/logic_app_workflow"]
env:
  ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
  RESOURCE_GROUP_NAME: NetworkWatcherRG

jobs: 
  build-and-deploy: 
    runs-on: ubuntu-latest

    steps:
      - name : az login
        id : az-login
        run : az login --service-principal -u ${{secrets.ARM_CLIENT_ID}} -p ${{secrets.ARM_CLIENT_SECRET}} --tenant ${{secrets.ARM_TENANT_ID}}

      - uses: azure/arm-deploy@v1
        name: deploy
        with:
          subscriptionId: $ARM_SUBSCRIPTION_ID
          resourceGroupName: $RESOURCE_GROUP_NAME
          template: ./ARMTemplates/LA_Standard_Basic.json
          # parameters: ./ARMTemplates/LA_Standard_Basic_Param.json 