# This is a basic workflow to help you get started with Actions

name: Create a Logic App

# Controls when the action will run. 
on:
  push: ["feature/logic_app_workflow"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: NetworkWatcherRG
          template: ./ARMTemplates/LA_Standard_Basic.json
          parameters: ./ARMTemplates/LA_Standard_Basic_Param.json